baseurl = "/"
# languageCode = "en-us"
languageLang = "en"
title = "Homepage"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]


# Configure Menu
# See docs here: https://gohugo.io/content-management/menus/

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"


# Configure Languages
# See options here: https://gohugo.io/content-management/multilingual/#configuring-multilingual-mode
defaultContentLangauge = "en"

[languages]
  [languages.en]
    languageName = "English"
      weight = 1

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/about-us"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "our-story"
        name = "Our Story"
        url = "/about/about-us#our-story"
        parent = "about"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "get-to-know-us"
        name = "Get to know us"
        url = "/about/about-us#get-to-know-us"
        parent = "about"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "our-supporters"
        name = "Our Supporters"
        url = "/about#our-supporters"
        parent = "about"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "programs"
        name = "Programs"
        url = "/programs"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "get-involved"
        name = "Get Involved"
        url = "/get-involved"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "student-placement"
        name = "Student Placement"
        url = "/get-involved#student-placement"
        parent = "get-involved"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "job-opportunities"
        name = "Job Opportunities"
        url = "/get-involved#job-opportunities"
        parent = "get-involved"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "volunteer"
        name = "Volunteer"
        url = "/get-involved#volunteer"
        parent = "get-involved"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources"
        weight = 4
  [languages.fr]
    languageName = "Français"
    weight = 2
    [languages.fr.menu]

      [[languages.fr.menu.main]]
        name = "Accueil"
        url = "/"
        weight = 0
  [languages.iu]
    languageName = "Inuktitut"
    title = "Sirivik IU"
    weight = 3
    [languages.iu.menu]

      [[languages.iu.menu.main]]
        name = "Home IU"
        url = "/"
        weight = 0