backend:
  name: git-gateway
  repo: liminalfun/sirivik
  branch: main

local_backend: true

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
# publish_mode: editorial_workflow

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [en, fr, iu]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections: # A list of collections the CMS should be able to edit
  - name: "programs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Programs" # Used in the UI, ie.: "New Post"
    folder: "site/content/programs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    i18n: true # Enable i18n for this file
    fields: # The fields each document in this collection have
      - {label: "Show this Program", name: "show", widget: "boolean", default: true}
      - {label: "Page Title", name: "title", widget: "string", i18n: true}
      - {label: "Featured Image", name: "image_ft", widget: "image", required: false, i18n: duplicate}
      - {label: "Program Title", name: "program-title", widget: "string", i18n: true}
      - {label: "Program Description", name: "description", widget: "markdown", i18n: true}
      - {label: "Testimonial", name: "testimonial", widget: "object", i18n: true, fields: [
        {label: "Testimonial Label", name: "label", widget: "string", i18n: true, default: "Testimonial"},
        {label: "Quote", name: "quote", widget: "text", i18n: true},
        {label: "Citation", name: "citation", widget: "string", i18n: true}
      ]}
      - {label: "Image 1", name: "image_1", widget: "image", required: false, i18n: duplicate}
      - {label: "Image 2", name: "image_2", widget: "image", required: false, i18n: duplicate}
      - {label: "Image 3", name: "image_3", widget: "image", required: false, i18n: duplicate}
      - {label: "Image 4", name: "image_4", widget: "image", required: false, i18n: duplicate}
      - {label: "Participate Card", name: "participate", widget: "object", i18n: true, fields: [
        {label: "Heading", name: "heading", widget: "string", i18n: true, required: false},
        {label: "Button 1", name: "btn_1", widget: "string", i18n: true, required: false, default: "Join Program"},
        {label: "Button 2", name: "btn_2", widget: "string", i18n: true, required: false, default: "Donate"}
      ]}
  - name: "pages"
    label: "Pages"
    i18n:
      structure: single_file
      locales: [en, fr, iu]
    files:
      - file: "site/content/home"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Hero section, name: hero, widget: object, fields: [
            {label: Featured Image, name: image, widget: image, i18n: duplicate, required: false},
            {label: Title, name: title, widget: string, i18n: true, required: false},
            {label: Subtitle, name: subtitle, widget: string, i18n: true, required: false},
            {label: Button Text, name: button, widget: string, i18n: true, required: false}
          ]}
          - {label: Fact section, name: fact, widget: object, fields: [
            {label: Section Title, name: title, widget: string, i18n: true, required: false},
            {label: Fact Card, name: card-info, widget: list, fields: [
              {label: Icon, name: icon, widget: image, i18n: duplicate, required: false},
              {label: Number or Percentage, name: number, widget: string, i18n: true, required: false},
              {label: Fact, name: fact, widget: text, i18n: true, required: false}
              ]}
          ]}
          - {label: Mission section, name: mission, widget: object, fields: [
            {label: Image, name: image, widget: image, i18n: duplicate, required: false},
            {label: Title, name: title, widget: string, i18n: true, required: false},
            {label: Subtitle, name: subtitle, widget: string, i18n: true, required: false}
          ]}
          - {label: Featured section, name: featured, widget: object, fields: [
            {label: Image, name: image, widget: image, i18n: duplicate, required: false},
            {label: Title, name: title, widget: string, i18n: true, required: false},
            {label: Subtitle, name: subtitle, widget: string, i18n: true, required: false},
            {label: Button Text, name: button, widget: string, i18n: true, required: false}
          ]}
          - {label: Programs section, name: programs, widget: object, fields: [
            {label: Section Title, name: title, widget: string, i18n: true, required: false},
            {label: Subtitle, name: subtitle, widget: string, i18n: true, required: false},
            {label: Featured Programs, name: featured-programs, widget: relation, collection: program, search_fields: ['title'], value_field: title, multiple: true, required: false}
          ]}
          - {label: Supportors section, name: supporters, widget: object, fields: [
            {label: Section Title, name: title, widget: string, i18n: true, required: false},
            {label: Subtitle, name: subtitle, widget: string, i18n: true, required: false},
            {label: Logos, name: logos, widget: image, multiple: true, required: false}
          ]}
          - {label: Get Involved section, name: get-involved, widget: object, fields: [
            {label: Section Title, name: title, widget: string, i18n: true, required: false},
            {label: Subtitle, name: subtitle, widget: text, i18n: true, required: false},
            {label: Get Involved Card, name: card-get-involved, widget: list, fields: [
              {label: Icon, name: icon, widget: image, i18n: duplicate, required: false},
              {label: Card Title, name: title, widget: string, i18n: true, required: false},
              {label: Card Subtitle, name: subtitle, widget: text, i18n: true, required: false},
              {label: Card Link Text, name: link-text, widget: string, i18n: true, required: false}
              ]}
          ]}
      - file: "site/content/about"
        label: "About Page"
        name: "about"
        i18n: true
        fields:
          - {label: Image, name: image, widget: image, i18n: duplicate}
          # - {label: "Our Story", name: our-story, widget: object, i18n: true, fields: [
          #     {label: "Heading", name: "heading", widget: string, i18n: true}, 
          #     {label: "Description", name: "description", widget: text, i18n: true}
          #   ]}
          # - {label: "Our Objectives", name: "our-objectives", widget: object, fields: [
          #   {label: "Heading", name: "heading", widget: string, i18n: true}, 
          #   {label: "Objectives", name: "objectives", widget: list, fields: [
          #     {label: "Icon", name: "icon", widget: image, i18n: duplicate},
          #     {label: "Description", name: "description", widget: string, i18n: true}
          #     ]}
          #   ]}
          # - {label: "Get to know us", name: "get-to-know-us", widget: object, fields: [
          #   {label: "Heading", name: "heading", widget: string, i18n: true},
          #   {label: "Our Staff", name: "our-staff", widget: object, fields: [
          #     {label: "Icon", name: "icon", widget: image, i18n: duplicate},
          #     {label: "Description", name: "description", widget: string, i18n: true}
          #     ]}
          #   ]}
      - file: "site/content/contact-us"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Logo, name: logo, widget: image, i18n: duplicate}
          - {label: Body, name: body, widget: markdown, i18n: true}
      - file: "site/content/get-involved"
        label: "Get Involved Page"
        name: "get-involved"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
  - name: "footer" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Footer" # Used in the UI, ie.: "New Post"
    folder: "site/content/footer" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    i18n: true # Enable i18n for this file
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "hidden", default: "footer", i18n: true}
      - {label: "Footer Message", name: "footer_msg", widget: "text", i18n: true}
      - {label: "Privacy Policy Label", name: "privacy", widget: "string", i18n: true}
      - {label: "Terms of Service Label", name: "terms", widget: "string", i18n: true}
      - {label: "Made by Label", name: "credit", widget: "string", i18n: true}
