[en]
languageName = "English"
weight = 1
title = "Sirivik"

[en.params]
logo_1 = "https://ucarecdn.com/a95dd8c2-beba-43ed-bbb5-edafe504a940/-/resize/800x/logo_nbgvca.svg"
logo_2 = "https://ucarecdn.com/22af8b3e-da0d-44f5-b247-cf155ffe5da7/-/resize/800x/wordmark_pu0ecp.svg"
footer = "Welcome to Sirivik! Thank you for visiting!"
description = "We’re building community through food, as a space for Inukjuamiut to learn, grow and share together."
preview = "https://ucarecdn.com/6b193af4-3ea1-4495-84c1-861fc96772c8/-/resize/800x/program_dropin_gallery_4_rbsxq5.jpg"

[en.menu]

[[en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1

[[en.menu.main]]
identifier = "programs"
name = "Programs"
url = "/programs"
weight = 2

[[en.menu.main]]
identifier = "get-involved"
name = "Get Involved"
url = "/get-involved"
weight = 3

[[en.menu.main]]
identifier = "resources"
name = "Resources"
url = "/resources"
weight = 4

[[en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 5

[[en.menu.contribute]]
identifier = "contribute"
name = "Donate"
url = "/contribute"
weight = 1

[iu]
languageName = "Inuktitut"
languagePrefix = "iu"
weight = 3
title = "ᓯᕆᕕᒃ"

[iu.params]
logo_1 = "https://ucarecdn.com/a95dd8c2-beba-43ed-bbb5-edafe504a940/-/resize/800x/logo_nbgvca.svg"
logo_2 = "https://ucarecdn.com/22af8b3e-da0d-44f5-b247-cf155ffe5da7/-/resize/800x/wordmark_pu0ecp.svg"
footer = ""
preview = "https://ucarecdn.com/6b193af4-3ea1-4495-84c1-861fc96772c8/-/resize/800x/program_dropin_gallery_4_rbsxq5.jpg"
description = "ᐃᓅᖃᑎᒌᓐᓂᒥᒃ ᓄᐃᑦᓯᕙᓪᓕᐊᕗᒍᑦ ᓂᕿᒥᒃ ᐊᕐᖁᑎᖃᑦᓱᑕ, ᐃᓄᑦᔪᐊᒥᐅᑦ ᐃᓕᑦᓯᒋᐊᕐᕕᒋᔭᖓᓂ, ᐱᕈᕐᐸᓕᐊᖃᑎᒌᕝᕕᖓᓂ ᐊᒻᒪᓗ ᐊᕕᖃᑎᒌᕝᕕᒋᔭᖓᓂ."

[iu.menu]

[[iu.menu.main]]
identifier = "about"
name = "ᑭᒡᒐᑐᕈᑎᖏᑦ"
url = "/about"
weight = 1

[[iu.menu.main]]
identifier = "programs"
name = "ᑭᒡᒐᑐᕈᑏᑦ"
weight = 2

[[iu.menu.main]]
identifier = "get-involved"
name = "ᑲᒪᖃᑕᐅᖁᔨᓂᕐᒧᑦ ᖁᑉᐱᒐᖅ"
url = "/get-involved"
weight = 3

[[iu.menu.main]]
identifier = "resources"
name = "ᐃᑲᔫᑎᑦᓭᑦ"
url = "/resources"
weight = 4

[[iu.menu.main]]
identifier = "contact"
name = "ᐅᖄᕕᐅᒍᓐᓇᑐᑦ"
url = "/contact"
weight = 5

[[iu.menu.contribute]]
identifier = "contribute"
name = "ᑐᓂᕐᕈᓯᐅᑏᑦ"
url = "/contribute"
weight = 1

[fr]
languageName = "Français"
languagePrefix = "fr"
weight = 2
title = "Sirivik"

[fr.params]
logo_1 = "https://ucarecdn.com/a95dd8c2-beba-43ed-bbb5-edafe504a940/-/resize/800x/logo_nbgvca.svg"
logo_2 = "https://ucarecdn.com/22af8b3e-da0d-44f5-b247-cf155ffe5da7/-/resize/800x/wordmark_pu0ecp.svg"
footer = "FR translation: Welcome to Sirivik! Thank you for visiting!"
preview = "https://ucarecdn.com/6b193af4-3ea1-4495-84c1-861fc96772c8/-/resize/800x/program_dropin_gallery_4_rbsxq5.jpg"
description = "Nous développons l’esprit de communauté à travers l’alimentation, dans cet endroit pour apprendre, grandir et partager."

[fr.menu]

[[fr.menu.main]]
identifier = "about"
name = "À propos"
url = "/about"
weight = 1

[[fr.menu.main]]
identifier = "programs"
name = "Programmes"
weight = 2

[[fr.menu.main]]
identifier = "get-involved"
name = "Get Involved"
url = "/get-involved"
weight = 3

[[fr.menu.main]]
identifier = "resources"
name = "Ressources"
url = "/resources"
weight = 4

[[fr.menu.main]]
identifier = "contact"
name = "Contactez"
url = "/contact"
weight = 5

[[fr.menu.contribute]]
identifier = "contribute"
name = "Contribuer"
url = "/contribute"
weight = 1